sudo: false
dist: xenial
language: python
cache: pip
python:
  - "nightly"
install: pip install -U $DEPS pytest pytest-asyncio flaky structlog
script: pytest
env:
  matrix:
    - DEPS=aiohttp
matrix:
  fast_finish: true

addons:
  apt:
    packages:
    - libgnutls-dev
