name: run mypy
on: [push, pull_request]
jobs:
  build:
    name: run mypy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install deps
      run: pip3 install -U tornado pytest pytest-asyncio pytest-httpbin flaky structlog toml aiohttp httpx mypy
    - name: Run mypy
      run: PATH=$HOME/.local/bin:$PATH mypy nvchecker nvchecker_source tests
